const stocks = [
  {
    symbol: 'AAPL',
    companyName: 'Apple Inc.',
    price: 175.25,
    previousClose: 172.75,
    change: 2.50,
    changePercent: 1.45,
  },
  {
    symbol: 'MSFT',
    companyName: 'Microsoft Corporation',
    price: 330.12,
    previousClose: 329.37,
    change: 0.75,
    changePercent: 0.23,
  },
  {
    symbol: 'GOOGL',
    companyName: 'Alphabet Inc.',
    price: 128.55,
    previousClose: 130.10,
    change: -1.55,
    changePercent: -1.19,
  },
  {
    symbol: 'AMZN',
    companyName: 'Amazon.com Inc.',
    price: 132.15,
    previousClose: 131.90,
    change: 0.25,
    changePercent: 0.19,
  },
  {
    symbol: 'TSLA',
    companyName: 'Tesla, Inc.',
    price: 252.70,
    previousClose: 258.10,
    change: -5.40,
    changePercent: -2.09,
  },
  {
    symbol: 'META',
    companyName: 'Meta Platforms, Inc.',
    price: 298.67,
    previousClose: 295.50,
    change: 3.17,
    changePercent: 1.07,
  },
  {
    symbol: 'NFLX',
    companyName: 'Netflix, Inc.',
    price: 393.25,
    previousClose: 390.10,
    change: 3.15,
    changePercent: 0.81,
  },
  {
    symbol: 'NVDA',
    companyName: 'NVIDIA Corporation',
    price: 445.20,
    previousClose: 440.35,
    change: 4.85,
    changePercent: 1.10,
  },
  {
    symbol: 'DIS',
    companyName: 'The Walt Disney Company',
    price: 93.45,
    previousClose: 92.75,
    change: 0.70,
    changePercent: 0.75,
  },
  {
    symbol: 'JPM',
    companyName: 'JPMorgan Chase & Co.',
    price: 142.80,
    previousClose: 143.25,
    change: -0.45,
    changePercent: -0.31,
  },
];

module.exports = { stocks }; 